language: php

php:
   - 5.3

env:
   global:
      - secure: "Z0rvDF/7cIrkHPNZ7GkOMgKiW7adoQTwA04a5lbl2zZs55HlaiETaaNexOZh\njCTvmdgKgxxFX74NAcB0rKKnhhU9v07uDrMjtpcUGhru5+iiJxhTu4v16FyW\n+Oze/izPsgKi8DjxGX6xtNeCUlO37jCGFYgZPwT4UeYPEfYnpLg="

before_script:
   - wget http://getcomposer.org/composer.phar
   - sh -c "if $TRAVIS_SECURE_ENV_VARS; then php composer.phar config github-oauth.github.com $GITHUB_OAUTH_TOKEN; else php composer.phar config preferred-install source; fi"
   - php composer.phar update --no-interaction

script:
   - ant CI-build
